name: "Black Duck Sarif Formatter"
description: "Will use Black Duck API to create sarif format outputfile from it."
author: Jouni Lehto
branding:
  icon: code
  color: blue
inputs:
  blackduck_log_level:
    description: Logging level
    default: DEBUG
    required: false
  blackduck_url:
    description: "Black DuckURL"
    required: true
  blackduck_apiToken:
    description: "Black Duck Access token"
    required: true
  blackduck_project:
    description: "Black Duck project name"
    required: false
    default: ${{github.repository}}
  blackduck_version:
    description: "Black Duck project version name"
    required: false
    default: ${{github.ref_name}}
  blackduck_policy_categories:
    description: "Comma separated list of policy categories, which violations will affect. Options are [COMPONENT,SECURITY,LICENSE,UNCATEGORIZED,OPERATIONAL], default=SECURITY,LICENSE"
    required: false
    default: SECURITY,LICENSE #Options are [COMPONENT,SECURITY,LICENSE,UNCATEGORIZED,OPERATIONAL]
  blackduck_outputFile:
    description: "Filename with path where it will be created, example: github.workspace/blackduckFindings.sarif.json (default)"
    default: ${{github.workspace}}/blackduckFindings.sarif.json
    required: false
  blackduck_policies:
    description: "If given, policy information is added"
    default: "false"
    required: false
  blackduck_iac:
    description: "If given, iac findings are added"
    default: "false"
    required: false
  blackduck_scan_full:
    description: "false for rapid scan results and true for intelligent scan, default false"
    default: "false"
    required: false
  blackduck_scanOutputPath:
    description: "If blackduck_scan_full = false, then this is required. Rapid scan output folder. You must specify scan output folder with --detect.scan.output.path \
            when running the Rapid scan with Black Duck and then give the same folder here, if you want to have rapid scan results as a sarif format report. \
            default is github.repository/bd_scan"
    default: ${{github.repository}}/bd_scan
    required: false
  blackduck_toolname_for_sarif_full:
    description: "Given name is used for sarif tool name for Black Duck full scan results. Default is Synopsys Black Duck Intelligent"
    required: false
    default: "Synopsys Black Duck Intelligent"
  blackduck_toolname_for_sarif_rapid:
    description: "Given name is used for sarif tool name for Black Duck rapid scan results. Default is Synopsys Black Duck Rapid"
    required: false
    default: "Synopsys Black Duck Rapid"

runs:
  using: composite
  steps:
    # Run the Python script
    - if: ${{inputs.blackduck_scan_full == 'true'}}
      run: |
        pip3 install blackduck requests
        python3 ${{github.action_path}}/blackduckResultsToSarif.py --toolNameforSarif="${{inputs.blackduck_toolname_for_sarif_full}}" --add_iac=${{inputs.blackduck_iac}} --policies=${{inputs.blackduck_policies}} --outputFile=${{inputs.blackduck_outputFile}} --url=${{inputs.blackduck_url}} --token=${{inputs.blackduck_apiToken}} --project=${{inputs.blackduck_project}} --version=${{inputs.blackduck_version}} --policyCategories="${{inputs.blackduck_policy_categories}}" --log_level=${{inputs.blackduck_log_level}}
      shell: bash
    - if: ${{inputs.blackduck_scan_full == 'false'}}
      run: |
        pip3 install blackduck
        python3 ${{github.action_path}}/blackduckRapidResultsToSarif.py --toolNameforSarif="${{inputs.blackduck_toolname_for_sarif_rapid}}" --scanOutputPath=${{inputs.blackduck_scanOutputPath}} --policies=${{inputs.blackduck_policies}} --outputFile=${{inputs.blackduck_outputFile}} --url=${{inputs.blackduck_url}} --token=${{inputs.blackduck_apiToken}} --policyCategories="${{inputs.blackduck_policy_categories}}" --log_level=${{inputs.blackduck_log_level}}
      shell: bash
